import { useState } from 'react';
import { useDataStore } from '../store/dataStore';
import type { PaymentRecord } from '../types';
import { Search, Download, Filter, CreditCard, CheckCircle, Clock, AlertCircle } from 'lucide-react';
import jsPDF from 'jspdf';
import toast from 'react-hot-toast';

const BATCHES = ['', 'May 2024 Batch', 'September 2024 Batch', 'January 2025 Batch', 'May 2025 Batch'];

export default function PaymentsPage() {
  const { students, modules } = useDataStore();
  const [search, setSearch] = useState('');
  const [filterBatch, setFilterBatch] = useState('');
  const [filterModule, setFilterModule] = useState('');
  const [filterStatus, setFilterStatus] = useState('');

  const allPayments: (PaymentRecord & { studentName: string })[] = students.flatMap(s =>
    s.payments.map(p => ({ ...p, studentName: s.name }))
  );

  const filtered = allPayments.filter(p => {
    const matchSearch = !search || p.studentName.toLowerCase().includes(search.toLowerCase()) || p.receiptNo.toLowerCase().includes(search.toLowerCase());
    const matchBatch = !filterBatch || p.batch === filterBatch;
    const matchModule = !filterModule || p.moduleId === filterModule;
    const matchStatus = !filterStatus || p.status === filterStatus;
    return matchSearch && matchBatch && matchModule && matchStatus;
  });

  const totalPaid = filtered.filter(p => p.status === 'paid').reduce((sum, p) => sum + p.amount, 0);
  const totalPending = filtered.filter(p => p.status !== 'paid').reduce((sum, p) => sum + p.amount, 0);

  const generatePaymentSlip = (payment: PaymentRecord & { studentName: string }) => {
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a6' });
    const w = pdf.internal.pageSize.getWidth();

    // Header
    pdf.setFillColor(79, 70, 229);
    pdf.rect(0, 0, w, 20, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('EduAdmin Pro', w / 2, 8, { align: 'center' });
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.text('Payment Receipt', w / 2, 14, { align: 'center' });

    // Body
    pdf.setTextColor(0, 0, 0);
    pdf.setFontSize(9);
    let y = 28;
    const lines: [string, string][] = [
      ['Receipt No:', payment.receiptNo],
      ['Student Name:', payment.studentName],
      ['Student ID:', payment.studentId],
      ['Module:', payment.moduleName],
      ['Batch:', payment.batch],
      ['Amount:', `LKR ${payment.amount.toLocaleString()}`],
      ['Payment Method:', payment.method.toUpperCase()],
      ['Payment Date:', payment.paidDate],
      ['Status:', payment.status.toUpperCase()],
    ];
    lines.forEach(([label, value]) => {
      pdf.setFont('helvetica', 'bold');
      pdf.text(label, 10, y);
      pdf.setFont('helvetica', 'normal');
      pdf.text(value, 55, y);
      y += 8;
    });

    // Footer
    pdf.setDrawColor(200, 200, 200);
    pdf.line(10, y + 2, w - 10, y + 2);
    pdf.setFontSize(7);
    pdf.setTextColor(150, 150, 150);
    pdf.text('Generated by EduAdmin Pro · Thank you for your payment!', w / 2, y + 8, { align: 'center' });

    pdf.save(`receipt-${payment.receiptNo}.pdf`);
    toast.success('Receipt downloaded!');
  };

  const generateAllPDF = () => {
    if (filtered.length === 0) { toast.error('No records to export'); return; }
    const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
    const pageW = pdf.internal.pageSize.getWidth();

    pdf.setFillColor(79, 70, 229);
    pdf.rect(0, 0, pageW, 18, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('EduAdmin Pro — Payment Report', pageW / 2, 11, { align: 'center' });

    const headers = ['Receipt No', 'Student', 'Module', 'Batch', 'Amount', 'Method', 'Date', 'Status'];
    const rows = filtered.map(p => [p.receiptNo, p.studentName, p.moduleName, p.batch, `LKR ${p.amount.toLocaleString()}`, p.method, p.paidDate, p.status]);

    let y = 30;
    const colWidths = [30, 45, 30, 40, 25, 20, 25, 20];
    let x = 10;

    // Header row
    pdf.setFillColor(240, 240, 255);
    pdf.rect(8, y - 5, pageW - 16, 8, 'F');
    pdf.setTextColor(79, 70, 229);
    pdf.setFontSize(8);
    headers.forEach((h, i) => { pdf.setFont('helvetica', 'bold'); pdf.text(h, x, y); x += colWidths[i]; });
    y += 6;

    pdf.setTextColor(50, 50, 50);
    rows.forEach(row => {
      if (y > 190) { pdf.addPage(); y = 20; }
      x = 10;
      row.forEach((cell, i) => { pdf.setFont('helvetica', 'normal'); pdf.setFontSize(7.5); pdf.text(cell, x, y); x += colWidths[i]; });
      y += 7;
      pdf.setDrawColor(230, 230, 230);
      pdf.line(8, y - 2, pageW - 8, y - 2);
    });

    pdf.save('payment-report.pdf');
    toast.success('Report exported!');
  };

  const statusIcon = (s: string) => s === 'paid'
    ? <CheckCircle className="w-3.5 h-3.5 text-emerald-500" />
    : s === 'pending' ? <Clock className="w-3.5 h-3.5 text-amber-500" />
      : <AlertCircle className="w-3.5 h-3.5 text-red-500" />;

  const statusColor = (s: string) => s === 'paid' ? 'bg-emerald-100 text-emerald-700' : s === 'pending' ? 'bg-amber-100 text-amber-700' : 'bg-red-100 text-red-700';

  return (
    <div className="p-6">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-800">Payments</h1>
          <p className="text-gray-500 text-sm">{allPayments.length} total records</p>
        </div>
        <button onClick={generateAllPDF} className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-xl text-sm font-medium transition-colors">
          <Download className="w-4 h-4" /> Export PDF
        </button>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        <div className="bg-white rounded-2xl p-4 border border-gray-100 shadow-sm">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-emerald-100 rounded-xl flex items-center justify-center"><CheckCircle className="w-5 h-5 text-emerald-600" /></div>
            <div><p className="text-sm text-gray-500">Total Collected</p><p className="text-xl font-bold text-gray-800">LKR {totalPaid.toLocaleString()}</p></div>
          </div>
        </div>
        <div className="bg-white rounded-2xl p-4 border border-gray-100 shadow-sm">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-amber-100 rounded-xl flex items-center justify-center"><Clock className="w-5 h-5 text-amber-600" /></div>
            <div><p className="text-sm text-gray-500">Pending</p><p className="text-xl font-bold text-gray-800">LKR {totalPending.toLocaleString()}</p></div>
          </div>
        </div>
        <div className="bg-white rounded-2xl p-4 border border-gray-100 shadow-sm">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-indigo-100 rounded-xl flex items-center justify-center"><CreditCard className="w-5 h-5 text-indigo-600" /></div>
            <div><p className="text-sm text-gray-500">Filtered Records</p><p className="text-xl font-bold text-gray-800">{filtered.length}</p></div>
          </div>
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-col sm:flex-row gap-3 mb-5">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
          <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search student name or receipt no..."
            className="w-full pl-10 pr-4 py-2.5 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 text-sm bg-white" />
        </div>
        <div className="flex items-center gap-2">
          <Filter className="w-4 h-4 text-gray-400 flex-shrink-0" />
          <select value={filterBatch} onChange={e => setFilterBatch(e.target.value)} className="px-3 py-2.5 border border-gray-200 rounded-xl text-sm bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500">
            {BATCHES.map(b => <option key={b} value={b}>{b || 'All Batches'}</option>)}
          </select>
          <select value={filterModule} onChange={e => setFilterModule(e.target.value)} className="px-3 py-2.5 border border-gray-200 rounded-xl text-sm bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500">
            <option value="">All Modules</option>
            {modules.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}
          </select>
          <select value={filterStatus} onChange={e => setFilterStatus(e.target.value)} className="px-3 py-2.5 border border-gray-200 rounded-xl text-sm bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500">
            <option value="">All Status</option>
            <option value="paid">Paid</option>
            <option value="pending">Pending</option>
            <option value="overdue">Overdue</option>
          </select>
        </div>
      </div>

      {/* Table */}
      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b border-gray-100 bg-gray-50">
                {['Receipt No', 'Student', 'Module', 'Batch', 'Amount', 'Method', 'Date', 'Status', 'Action'].map(h => (
                  <th key={h} className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {filtered.map(p => (
                <tr key={p.id} className="hover:bg-gray-50 transition-colors">
                  <td className="px-4 py-3 text-xs font-mono text-gray-500">{p.receiptNo}</td>
                  <td className="px-4 py-3 text-sm font-medium text-gray-800">{p.studentName}</td>
                  <td className="px-4 py-3 text-sm text-gray-600">{p.moduleName}</td>
                  <td className="px-4 py-3 text-xs text-gray-500">{p.batch}</td>
                  <td className="px-4 py-3 text-sm font-semibold text-gray-800">LKR {p.amount.toLocaleString()}</td>
                  <td className="px-4 py-3 text-xs text-gray-500 capitalize">{p.method}</td>
                  <td className="px-4 py-3 text-xs text-gray-500">{p.paidDate}</td>
                  <td className="px-4 py-3">
                    <span className={`inline-flex items-center gap-1 text-xs px-2 py-0.5 rounded-full font-medium ${statusColor(p.status)}`}>
                      {statusIcon(p.status)} {p.status}
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    <button onClick={() => generatePaymentSlip(p)}
                      className="flex items-center gap-1 text-xs text-indigo-600 hover:text-indigo-700 font-medium">
                      <Download className="w-3 h-3" /> Slip
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          {filtered.length === 0 && (
            <div className="text-center py-16 text-gray-400">
              <CreditCard className="w-12 h-12 mx-auto mb-3 opacity-30" />
              <p>No payment records found</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
